"""Design tokens for the Gangware UI.

Single source of truth for UI colors, sizes, fonts, and spacing.
"""

# Global scale (0.72 ≈ 28% reduction). All px tokens derive from BASE * UI_SCALE
UI_SCALE = 0.72  # small uplift to remove subtle label clipping

# Helper (module-internal)
def _spx(n: float) -> int:
    try:
        return int(round(float(n) * UI_SCALE))
    except Exception:
        return int(n)

# Colors
CYAN = "#00DDFF"
ORANGE = "#FFB800"
TEXT_DEFAULT = "#D5DCE3"
STATUS_OK = "#31F37A"
BG_CARD_RGBA = "rgba(10,20,30,0.85)"
BG_SECTION_RGBA = "rgba(18,28,40,0.60)"
BORDER_CYAN = "rgba(0,221,255,0.40)"
BORDER_SECTION = "rgba(0,221,255,0.28)"
DIVIDER = "rgba(0,221,255,0.28)"
KEYCAP_BG = "rgba(15,30,45,0.92)"
KEYCAP_BORDER = "rgba(0,221,255,0.45)"
STATUSBOX_BG = "rgba(15,30,45,0.90)"
STATUSBOX_BORDER = "rgba(255,255,255,0.20)"

# Radii (BASE -> scaled px)
RADIUS_CARD_BASE = 14
RADIUS_SECTION_BASE = 10
RADIUS_KEYCAP_BASE = 10
RADIUS_TAB_BASE = 8
RADIUS_PRIMARY_BASE = 10

RADIUS_CARD = _spx(RADIUS_CARD_BASE)
RADIUS_SECTION = _spx(RADIUS_SECTION_BASE)
RADIUS_KEYCAP = _spx(RADIUS_KEYCAP_BASE)
RADIUS_TAB = _spx(RADIUS_TAB_BASE)
RADIUS_PRIMARY = _spx(RADIUS_PRIMARY_BASE)

# Fonts
FONT_STACK = "'Orbitron', 'Segoe UI', Arial, sans-serif"
TITLE_SIZE_BASE = 52
SECTION_SIZE_BASE = 27
SUBTITLE_SIZE_BASE = 15
FONT_SIZE_BASE = 17

TITLE_SIZE = _spx(TITLE_SIZE_BASE)
SECTION_SIZE = _spx(SECTION_SIZE_BASE)
SUBTITLE_SIZE = _spx(SUBTITLE_SIZE_BASE)
FONT_SIZE = _spx(FONT_SIZE_BASE)  # body font size

# Spacing & sizes (BASE -> scaled px)
TAB_MIN_HEIGHT_BASE = 40
TAB_PADDING_Y_BASE = 8
TAB_PADDING_X_BASE = 16
KEYCAP_PADDING_Y_BASE = 6
KEYCAP_PADDING_X_BASE = 12
SMALLBTN_PADDING_Y_BASE = 6
SMALLBTN_PADDING_X_BASE = 12

TAB_MIN_HEIGHT = _spx(TAB_MIN_HEIGHT_BASE)
TAB_PADDING_Y = _spx(TAB_PADDING_Y_BASE)
TAB_PADDING_X = _spx(TAB_PADDING_X_BASE)
KEYCAP_PADDING_Y = _spx(KEYCAP_PADDING_Y_BASE)
KEYCAP_PADDING_X = _spx(KEYCAP_PADDING_X_BASE)
SMALLBTN_PADDING_Y = _spx(SMALLBTN_PADDING_Y_BASE)
SMALLBTN_PADDING_X = _spx(SMALLBTN_PADDING_X_BASE)
